services:
  - type: web
    name: 4utoday-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: 4utoday-db
          property: connectionString

databases:
  - name: 4utoday-db
    plan: free
    databaseName: 4utoday
    user: 4utoday_user
