services:
  - type: web
    name: fouru-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromContext: instanceUrl
      - key: DATABASE_URL
        fromDatabase:
          name: fouru-db
          property: connectionString

databases:
  - name: fouru-db
    plan: free
    databaseName: fouru_today_db
    user: fouru_admin
