services:
  - type: web
    name: futoday-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: futoday-db
          property: connectionString

databases:
  - name: futoday-db
    plan: free
    databaseName: futoday_db
    user: futoday_user
